package cleoni.adv;

/** Custom Exception for proper dealing of errors generated by the game engine
 * @author:
 */
public class DimxException extends Exception {

/**
 * DimxException Constructor
 * @param s java.lang.String
 */
public DimxException(String s) {
	super(s);
}
}
